name: alpaca
description: A Dart implementation of the Alpaca project
version: 1.0.0
homepage: https://github.com/shamblett/alpaca

funding:
 - https://www.darticulate.com/#funding

publish_to: 'none'

environment:
 sdk: '>=2.17.0 <3.0.0'

executables:
 chat:

dependencies:
 data: '^0.11.0'
 ffi: '^2.0.1'
 fixnum: '^1.1.0'
 mt19937: '0.1.0'
 posix: '^4.1.0'

dev_dependencies:
 test: '^1.21.5'
 lints: '^2.0.0'
 ffigen: '^7.2.10'
 
 

