name: alpaca
description: A Dart implementation of the Alpaca project
version: 1.1.0
homepage: https://github.com/shamblett/alpaca

funding:
 - https://www.darticulate.com/#funding

publish_to: 'none'

environment:
 sdk: '>=3.0.0 <4.0.0'

executables:
 chat:

dependencies:
 data: '^0.11.0'
 ffi: '^2.0.2'
 fixnum: '^1.1.0'
 mt19937: '0.1.0'
 posix: '^5.0.0'
 stdlibc: '^0.1.2'

dev_dependencies:
 test: '^1.21.5'
 lints: '^2.0.1'
 ffigen: '^8.0.1'
 
 

